spring:
  application:
    name: p2p-DataService
  dubbo:
    server: true
    registry: zookeeper://192.168.164.130:2181

  datasource:
    url: jdbc:mysql://192.168.164.130:3306/springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 119
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 192.168.164.130
    port: 6379
    password: 119

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:slf4j.xml
